{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rma-portal.serviceAccountName" . }}
  labels:
{{ include "rma-portal.labels" . | nindent 4 }}
{{- end -}}
